name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        runs-on: self-hosted
        steps:
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        permissions:
          contents: write
        runs-on: self-hosted
        steps:
          - name: Run full test
            run: export PATH=/home/crosscompilertoolchain/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu/bin:$PATH
          - name: Run manual linux
            run: ./home/nbuchanan/assignment-1-nbuchanan745/finder-app/manual-linux.sh
